### ISSUE TITLE
uploading single spectra seems to fail now

### ISSUE THREAD

**Issue by lutzfischer** [Rappsilber-Laboratory/xiSPEC_website#17]
get an error about a missing ;
firefox:
SyntaxError: missing ; before statement[Learn More]  viewSpectrum.php:74:74
Chromium:
viewSpectrum.php:74 Uncaught SyntaxError: Unexpected token :

Peptide:SEVAHR
Peaks:
110.0712	2,466.5740	
110.7208	902.2990
117.4302	848.3815
119.5550	1,063.8896	
128.0510	1,274.5342	
129.1021	1,911.1145	
134.0958	1,007.9410	
175.1189	2,100.2012	
189.0872	1,534.6859	
193.3177	1,206.5647	
206.1267	1,478.0295	
211.0350	1,502.2489	
267.6374	2,178.4194	
269.1130	1,730.1249	
276.6421	5,210.5532	
344.9759	5,471.3921	
345.9762	3,081.8931	
346.9739	35,159.7773
347.9749	1,616.8217
349.2736	1,673.4293	
372.9158	1,711.1366	
418.0348	5,000.5859	
435.0449	1,967.5284	
448.2164	1,871.0549	
483.2810	1,565.2408	
561.2708	1,884.1422	
698.3585	17,252.0527
699.3571	2,943.0547	
866.2133	1,469.6975	
1,009.5244	1,873.4841	
charge: 3
error:20 ppm

**Comment by lutzfischer** [comment]
Just realised the error comes from the comma in the numbers that after cleaning up the spectrum (e.g. removing trailing spaces) it worked but failed on some peaks. Then I realised it is down to the commas in the numbers.

**Comment by lars-kolbowski** [comment]
should work after removing the commas.
