### ISSUE TITLE
Unable to upload data to XiVIEW

### ISSUE THREAD

**Issue by pdoppler** [Rappsilber-Laboratory/xiSPEC_website#36]
log id: 76di0igvngcvt5lskeusa0ps44_1532268989.log (include this in the github issue)
error type: Error
message: Inconsistent number of protein to decoy values for Protein1 and Decoy1 in row 431!
id: undefined

I tried now several times with different fasta, mgf files and completely other XiSearch results, but always showed this error.

I attended the EuPA Summer School of Advanced Proteomics in Vienna earlier this week and did the same steps with my data set now, but unfortunately, it did not work!

Thanks in advance!
Philipp

**Comment by pdoppler** [comment]
Hey Colin,
thanks for your fast reply!

I now did an XiSearch without the second very similar protein and uploaded a different file name and it worked!

Thanks a lot!
Philipp

**Comment by colin-combe** [comment]
>  incompatibility between the output of xiFDR and the input of xiVIEW 
this should be fixed now, ambiguous results output from xiFDR should be loadable in xiView
