### ISSUE TITLE
Labelling parent ion m/z

### ISSUE THREAD

**Issue by PhilipJBrownridge** [Rappsilber-Laboratory/xiSPEC_website#40]
Hello, please would it be possible to label the any residual precursor on the spectrum? Also neutral loss from precursor?
thanks
Philip

**Comment by lars-kolbowski** [comment]
Hi Philip,
any remaining precursor should be annotated in the spectrum if you select 'peptide' ion for annotation. So it should be done by default ("peptide, b, y" is the default setting).
Neutral losses also should get annotated of all selected ions. You can see check the neutral loss settings in the Spectrum Settings at the bottom below the modifications.

**Comment by PhilipJBrownridge** [comment]
That's awesome! Sorry to be slow but does neutral loss also cover neutral loss from precursor?
Thanks
Philip

Philip J Brownridge




On Tue, Jan 29, 2019 at 8:49 AM +0000, "lars-kolbowski" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Philip,
any remaining precursor should be annotated in the spectrum if you select 'peptide' ion for annotation. So it should be done by default ("peptide, b, y" is the default setting).
Neutral losses also should get annotated of all selected ions. You can see check the neutral loss settings in the Spectrum Settings at the bottom below the modifications.

**Comment by lars-kolbowski** [comment]
Yes it should since 'peptide ions' should be treated the same as other ions in terms of losses
