### ISSUE TITLE
Uncaught ReferenceError: specListTableView is not defined

### ISSUE THREAD

**Issue by levitsky** [Rappsilber-Laboratory/xiSPEC_website#44]
Hi,

I'm trying to use the SpectrumViewer website but I get an empty window and an error in the console:

![image](https://user-images.githubusercontent.com/3358268/139457252-1d2a2844-99d4-4e10-8712-af1c04c3af77.png)

The error says:
```
Uncaught ReferenceError: specListTableView is not defined
    at Object.success (TableWrapperView.js:110)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

How I'm getting the error:

1. I uploaded my own CSV and MGF files and got this;
2. I tried a PRIDE example by selecting two files from the suggested PRIDE dataset and also got this error;
3. I tried opening a pre-saved spectrum set from uploaded files that used to work before, with the same error.

I'm on Google Chrome Version 95.0.4638.69 (Official Build) (64-bit), but I get the same on Firefox. I also tried an incognito window to rule out any malicious effect of browser extensions.

**Comment by lars-kolbowski** [comment]
Thank you for catching this. Should be fixed now!
